### ISSUE TITLE
Version 3: registerToolbarItem.php failed to open stream

### ISSUE THREAD

**Issue by ghost** [tschikarski/shibboleth#10]
In version 3.0.2 there occurs an error in the logfile:

> Core: Error handler (BE): PHP Warning: include_once(/srv/www/html/typo3conf/ext/shibboleth/registerToolbarItem.php): failed to open stream: No such file or directory in /srv/www/typo3_src-7.6.10/typo3/sysext/backend/Classes/Controller/BackendController.php line 189

**Comment by tschikarski** [comment]
Version 3.0.3 should fix this error. On existing installations one has to clear the code cache. This typically happens automatically, if the extension is updated using the BE.
