### ISSUE TITLE
Login without Shibboleth not possible if Shibboleth session exists

### ISSUE THREAD

**Issue by ghost** [tschikarski/shibboleth#14]
When a user login via Shibboleth into the typo3 backend and is not yet enabled, he sees the page "You are not activated yet". If the user now wants to login via a local user and change the loginProvider to the default provider, he is able to see the normal login window. But now he can't log in even with correct username/password. There is always a message appearing, that the username/password is incorrect.

Desired behavior: either switching login-Provider shouldnt be possible or the login should work anyway and replace the shibboleth session.

**Comment by tschikarski** [comment]
Could not verify. Just tested on my system. TYPO3 allowed me to login with a local user, after I managed to get the classic login provider. However, I had to manually go to /typo3/?redirecttoshibboleth=no to get to the login page. Might be useful to have that as a link in the "not yet allowed html page".

**Comment by tschikarski** [comment]
Login logic has been improved in version 3.1. Please test with version 3.1.7 and re-open the issue, if the problem still persists.
