### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by stucki** [tschikarski/shibboleth#26]
There are lots of changes in the `3.0-dev` branch. It would be great to have a 3.0.4 release which includes these changes.

**Comment by ursbraem** [comment]
Just if anyone lands here out of the same reason as me: there's also https://packagist.org/packages/visol/shibboleth-auth

**Comment by tschikarski** [comment]
Uploaded 3.1.7

**Comment by tschikarski** [comment]
A new version is available: 3.1.7
